# Generated by Django 3.1.4 on 2021-02-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nama')),
            ],
        ),
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indoplaces.province')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('regency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indoplaces.regency')),
                ('name', models.CharField(max_length=50, verbose_name='Nama')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indoplaces.district')),
            ],
        ),
    ]
