# Generated by Django 4.0.7 on 2024-05-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_date', models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Tanggal Bayar')),
                ('start', models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Mulai Sewa')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.rent')),
            ],
        ),
    ]
