# Generated by Django 4.0.7 on 2024-05-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='start',
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_date',
            field=models.DateField(default=None, help_text='Format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(default=None, help_text='Format: YYYY-MM-DD'),
        ),
    ]
