# Generated by Django 4.0.7 on 2024-05-08 08:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_date', models.DateField(default=None)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Format: YYYY-MM-DD')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.house')),
                ('renter', models.ForeignKey(limit_choices_to={'groups__name': 'renter'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_date', models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Tanggal Bayar')),
                ('start', models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Mulai Sewa')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.rent')),
            ],
        ),
    ]
