# Generated by Django 4.0.7 on 2023-01-21 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, verbose_name='NIK KTP')),
                ('occupation', models.CharField(max_length=100, verbose_name='Pekerjaan')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('bank_account', models.CharField(blank=True, help_text='Bank yang digunakan', max_length=10, null=True, verbose_name='Bank')),
                ('bank_account_number', models.CharField(blank=True, help_text='Nomor rekening bank yang digunakan', max_length=50, null=True, verbose_name='Nomor Rekening')),
                ('photo_ktp', models.FileField(blank=True, null=True, upload_to=profile.models.profile_path)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Kepala Keluarga')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
