# Generated by Django 4.0.7 on 2024-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='NIK KTP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan'),
        ),
    ]
