# Generated by Django 4.0.7 on 2024-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profile_nik_alter_profile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nik',
            field=models.CharField(max_length=16, verbose_name='NIK KTP'),
        ),
    ]
