# Generated by Django 4.0.7 on 2024-05-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expense.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'owner'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('remark', models.CharField(max_length=200, verbose_name='Catatan')),
                ('receipt_photo', models.FileField(blank=True, null=True, upload_to=expense.models.expense_path)),
                ('expense_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='expense.expensetype')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.house')),
            ],
        ),
    ]
