# Generated by Django 2.1.7 on 2019-06-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_identityinfo_pob'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityinfo',
            name='bank_account',
            field=models.CharField(default='<bank>', help_text='Bank yang digunakan', max_length=10, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='identityinfo',
            name='bank_account_number',
            field=models.CharField(default='<bank number>', help_text='Nomor rekening bank yang digunakan', max_length=50, verbose_name='Nomor Rekening'),
        ),
    ]
