# Generated by Django 2.1.7 on 2019-06-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20190613_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinfo',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank yang digunakan', max_length=10, null=True, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Nomor rekening bank yang digunakan', max_length=50, null=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='pob',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Tempat Kelahiran'),
        ),
    ]
