# Generated by Django 2.2.2 on 2019-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20190613_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinfo',
            name='dob',
            field=models.DateField(help_text='Format: YYYY-MM-DD', verbose_name='Tanggal Lahir'),
        ),
    ]
