# Generated by Django 2.2.3 on 2019-08-13 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0005_auto_20190701_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityinfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_parent', to=settings.AUTH_USER_MODEL, verbose_name='Kepala Keluarga'),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='identity_address',
            field=models.CharField(max_length=110, null=True, verbose_name='Alamat Sesuai Identitas'),
        ),
    ]
