# Generated by Django 2.2.3 on 2019-08-20 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20190813_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Kepala Keluarga'),
        ),
    ]
