# Generated by Django 2.1.7 on 2019-05-25 16:38

from django.db import migrations, models
import django.db.models.deletion
import house.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.PositiveIntegerField(verbose_name='Biaya Pengeluaran')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('remark', models.CharField(max_length=200, verbose_name='Catatan')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='Nomor Kwitansi')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to=house.helpers.photo_path)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama')),
                ('address', models.CharField(max_length=300, verbose_name='Alamat')),
                ('pln_number', models.CharField(max_length=20, verbose_name='Nomor PLN')),
                ('owner', models.ForeignKey(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.PROTECT, to='person.IdentityInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga')),
                ('pay_date', models.DateField(default=None, verbose_name='Tanggal Bayar')),
                ('start', models.DateField(verbose_name='Mulai Sewa')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga')),
                ('billing_date', models.DateField(default=None, verbose_name='Tanggal Tagihan')),
                ('active', models.BooleanField(default=True, verbose_name='Status Sewa Aktif')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.House', verbose_name='Rumah')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.IdentityInfo', verbose_name='Penyewa')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.Rent'),
        ),
        migrations.AddField(
            model_name='expense',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.House'),
        ),
    ]
