# Generated by Django 4.0.7 on 2023-01-21 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import house.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indoplaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama')),
                ('address', models.CharField(max_length=300, verbose_name='Alamat')),
                ('pln_number', models.CharField(blank=True, max_length=20, verbose_name='Nomor PLN')),
                ('active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=house.models.house_dir)),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'owner'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indoplaces.village')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga')),
                ('billing_date', models.DateField(default=None, verbose_name='Tanggal Tagihan')),
                ('active', models.BooleanField(default=True, verbose_name='Status Sewa')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Format: YYYY-MM-DD', verbose_name='Awal Masuk')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.house', verbose_name='Rumah')),
                ('renter', models.ForeignKey(limit_choices_to={'groups__name': 'renter'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Penyewa')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga')),
                ('pay_date', models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Tanggal Bayar')),
                ('start', models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Mulai Sewa')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.rent')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipe Pengeluaran')),
                ('owner', models.ForeignKey(limit_choices_to={'groups__name': 'owner'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Rumah')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.PositiveIntegerField(verbose_name='Biaya Pengeluaran')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('remark', models.CharField(max_length=200, verbose_name='Catatan')),
                ('receipt_photo', models.FileField(blank=True, null=True, upload_to=house.models.expense_path)),
                ('expense_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='house.expensetype')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.house')),
            ],
        ),
    ]
