# Generated by Django 2.1.7 on 2019-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='renter',
            field=models.PositiveIntegerField(),
        ),
    ]
