# Generated by Django 2.2.5 on 2020-03-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_number',
        ),
    ]
