# Generated by Django 4.0.7 on 2024-05-11 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('name', 'owner')},
        ),
    ]
