# Generated by Django 4.0.7 on 2024-05-13 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0002_alter_house_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='house',
            name='name_lower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('name_lower', 'owner')},
        ),
    ]
