# Generated by Django 3.1.4 on 2021-02-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoplaces', '0001_initial'),
        ('house', '0002_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='price',
            new_name='nominal',
        ),
        migrations.AddField(
            model_name='house',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indoplaces.village'),
        ),
    ]
