# Generated by Django 4.0.7 on 2024-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_house_unique_together_house_name_lower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='pln_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
