# Generated by Django 2.1.7 on 2019-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190526_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rent',
            field=models.PositiveIntegerField(),
        ),
    ]
