# Generated by Django 2.1.7 on 2019-05-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190526_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.Rent'),
        ),
    ]
