# Generated by Django 2.1.7 on 2019-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20190526_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.PositiveIntegerField(),
        ),
    ]
