# Generated by Django 2.1.7 on 2019-05-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20190526_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.PROTECT, to='person.IdentityInfo'),
        ),
    ]
