# Generated by Django 2.1.7 on 2019-06-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20190526_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Tanggal Bayar'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start',
            field=models.DateField(help_text='Format: YYYY-MM-DD', verbose_name='Mulai Sewa'),
        ),
    ]
