# Generated by Django 2.2.3 on 2019-07-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20190611_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Format: YYYY-MM-DD', verbose_name='Awal Masuk'),
        ),
    ]
