# Generated by Django 2.2.3 on 2019-08-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_rent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start',
            field=models.DateField(default=None, help_text='Format: YYYY-MM-DD', verbose_name='Mulai Sewa'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status Sewa'),
        ),
    ]
