# Generated by Django 2.2.5 on 2019-11-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='house.ExpenseType'),
        ),
    ]
