# Generated by Django 3.1.4 on 2020-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
